# Generated by Django 4.1.6 on 2023-02-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_item_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.RemoveField(
            model_name='item',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
